// Full RDR2 main-story mission list, in canonical play order (Chapter 1
// through Epilogue 2). Save file headers store the exact mission title as
// readable text, so this is matched verbatim against that — see tracker/.
export const DEFAULT_MISSIONS = [
  // Chapter 1: Colter
  { name: "Outlaws from the West", chapter: "Chapter 1", location: "Colter" },
  { name: "Enter, Pursued by a Memory", chapter: "Chapter 1", location: "Colter" },
  { name: "Old Friends", chapter: "Chapter 1", location: "Colter" },
  { name: "The Aftermath of Genesis", chapter: "Chapter 1", location: "Colter" },
  { name: "Who the Hell is Leviticus Cornwall?", chapter: "Chapter 1", location: "Colter" },
  { name: "Eastward Bound", chapter: "Chapter 1", location: "Colter" },

  // Chapter 2: Horseshoe Overlook
  { name: "Polite Society, Valentine Style", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Americans at Rest", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "The First Shall Be Last", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Exit Pursued by a Bruised Ego", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Who Is Not Without Sin", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Money Lending and Other Sins I", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Money Lending and Other Sins II", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Money Lending and Other Sins III", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Paying a Social Call", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "A Quiet Time", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Blessed Are the Meek?", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "We Loved Once and True I", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "We Loved Once and True II", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "We Loved Once and True III", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "The Spines of America", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Pouring Forth Oil I", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Pouring Forth Oil II", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Pouring Forth Oil III", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "Pouring Forth Oil IV", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "A Fisher of Men", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "The Sheep and the Goats", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "An American Pastoral Scene", chapter: "Chapter 2", location: "Horseshoe Overlook" },
  { name: "A Strange Kindness", chapter: "Chapter 2", location: "Horseshoe Overlook" },

  // Chapter 3: Clemens Point
  { name: "Further Questions of Female Suffrage", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The New South", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The Course of True Love I", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The Course of True Love II", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The Course of True Love III", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "American Distillation", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Advertising, the New American Art", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "An Honest Mistake", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Horse Flesh for Dinner", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The Fine Joys of Tobacco", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Preaching Forgiveness as He Went", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Magicians for Sport", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Sodom? Back to Gomorrah", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Blessed Are the Peacemakers", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Friends in Very Low Places", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "A Short Walk in a Pretty Town", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "Blood Feuds, Ancient and Modern", chapter: "Chapter 3", location: "Clemens Point" },
  { name: "The Battle of Shady Belle", chapter: "Chapter 3", location: "Clemens Point" },

  // Chapter 4: Saint Denis
  { name: "The Joys of Civilization", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Angelo Bronte, a Man of Honor", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "No, No and Thrice, No", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Fatherhood and Other Dreams I", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Fatherhood and Other Dreams II", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "The Gilded Cage", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "A Fine Night of Debauchery", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Horsemen, Apocalypses", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Urban Pleasures", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Country Pursuits", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Revenge Is a Dish Best Eaten", chapter: "Chapter 4", location: "Saint Denis" },
  { name: "Banking, the Old American Art", chapter: "Chapter 4", location: "Saint Denis" },

  // Chapter 5: Guarma
  { name: "Welcome to the New World", chapter: "Chapter 5", location: "Guarma" },
  { name: "Savagery Unleashed", chapter: "Chapter 5", location: "Guarma" },
  { name: "Hell Hath No Fury", chapter: "Chapter 5", location: "Guarma" },
  { name: "A Kind and Benevolent Despot", chapter: "Chapter 5", location: "Guarma" },
  { name: "Paradise Mercifully Departed", chapter: "Chapter 5", location: "Guarma" },
  { name: "Dear Uncle Tacitus", chapter: "Chapter 5", location: "Guarma" },

  // Chapter 6: Beaver Hollow
  { name: "Icarus and Friends", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Of Men and Angels", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Do Not Seek Absolution I", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Do Not Seek Absolution II", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Visiting Hours", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The Course of True Love IV", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The Course of True Love V", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Just a Social Call", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "A Rage Unleashed", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The Delights of Van Horn", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The Bridge to Nowhere", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Archeology for Beginners", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Honor, Amongst Thieves", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Money Lending and Other Sins VI", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Money Lending and Other Sins VII", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Goodbye, Dear Friend", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The Fine Art of Conversation", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Favored Sons", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Mrs. Sadie Adler, Widow I", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Mrs. Sadie Adler, Widow II", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "The King's Son", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "My Last Boy", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Our Best Selves", chapter: "Chapter 6", location: "Beaver Hollow" },
  { name: "Red Dead Redemption", chapter: "Chapter 6", location: "Beaver Hollow" },

  // Epilogue 1: Pronghorn Ranch
  { name: "The Wheel", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Simple Pleasures", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Fatherhood for Beginners", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Farming for Beginners", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Old Habits", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Jim Milton Rides, Again?", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Fatherhood for Idiots", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Motherhood", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Gainful Employment", chapter: "Epilogue 1", location: "Pronghorn Ranch" },
  { name: "Home of the Gentry?", chapter: "Epilogue 1", location: "Pronghorn Ranch" },

  // Epilogue 2: Beecher's Hope
  { name: "Bare Knuckle Friendships", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "Home Improvement for Beginners", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "An Honest Day's Labors", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "The Tool Box", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "A New Jerusalem", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "A Quick Favor for an Old Friend", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "Uncle's Bad Day", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "Trying Again", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "A Really Big Bastard", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "A New Future Imagined", chapter: "Epilogue 2", location: "Beecher's Hope" },
  { name: "American Venom", chapter: "Epilogue 2", location: "Beecher's Hope" },
]
